"use strict";

/**
 * Mehrsprachige Strings und LLM-Prompts (de/en).
 *
 * Die deutsche QA-Variante ist bewusst wortgleich zum bisherigen qa-agent.js,
 * damit bestehende Reports unverändert reproduziert werden.
 */

const STRINGS = {
  de: {
    noConsoleIssues: "Keine Konsolen-Fehler oder Warnungen erkannt.",
    reportHeading: "QA-Report",
    consoleSection: "Konsolen-Logs",
    analysisSection: "LLM-Analyse",
    generatedBy: "Erzeugt von CUE-AGENT",
  },
  en: {
    noConsoleIssues: "No console errors or warnings detected.",
    reportHeading: "QA Report",
    consoleSection: "Console Logs",
    analysisSection: "LLM Analysis",
    generatedBy: "Generated by CUE-AGENT",
  },
};

const QA_SYSTEM_PROMPT = {
  de: `Du bist ein erfahrener QA-Experte. Analysiere den folgenden Screenshot und die zugehoerigen Browser-Konsolen-Logs einer Webseite. Identifiziere und beschreibe:

1. UI/UX-Fehler (z.B. falsche Ausrichtung, ueberlappende Elemente, unlesbarer Text)
2. Abgeschnittene oder ueberlaufende Elemente
3. Visuelle Bugs (z.B. fehlende Bilder, kaputtes Layout, falsche Farben)
4. Technische Fehler (basierend auf den Konsolen-Logs)
5. Allgemeine Verbesserungsvorschlaege zur Benutzerfreundlichkeit

Strukturiere deine Analyse klar mit Ueberschriften. Wenn keine Probleme gefunden werden, gib eine kurze positive Bewertung ab.`,
  en: `You are an experienced QA expert. Analyze the following screenshot and the accompanying browser console logs of a web page. Identify and describe:

1. UI/UX issues (e.g. misalignment, overlapping elements, unreadable text)
2. Cut-off or overflowing elements
3. Visual bugs (e.g. missing images, broken layout, wrong colors)
4. Technical errors (based on the console logs)
5. General usability improvement suggestions

Structure your analysis clearly with headings. If no issues are found, give a brief positive assessment.`,
};

function qaUserMessage(lang, url, consoleLogsText) {
  if (lang === "en") {
    return `Please analyze this web page (URL: ${url}).

Browser console logs:
\`\`\`
${consoleLogsText}
\`\`\`

The screenshot of the page is attached.`;
  }
  return `Bitte analysiere diese Webseite (URL: ${url}).

Browser-Konsolen-Logs:
\`\`\`
${consoleLogsText}
\`\`\`

Der Screenshot der Seite ist angehaengt.`;
}

function t(lang, key) {
  const l = STRINGS[lang] ? lang : "de";
  return STRINGS[l][key];
}

// Strukturierte Befunde als JSON (für QA-Loop & Release-Readiness)
const QA_STRUCTURED_PROMPT = {
  de: `Du bist ein erfahrener QA-Ingenieur. Analysiere den Screenshot und die Konsolen-Logs einer Webseite.
Antworte AUSSCHLIESSLICH mit gültigem JSON (kein Markdown, keine Erklärung davor/danach) in genau diesem Schema:
{
  "summary": "kurze Gesamtbewertung",
  "score": 0-100,
  "findings": [
    {
      "id": "kurz-eindeutig",
      "title": "knappe Überschrift",
      "severity": "low|medium|high|critical",
      "category": "ui|layout|visual|technical|accessibility|performance|content",
      "description": "was ist das Problem",
      "suggestedFix": "konkreter, umsetzbarer Lösungsvorschlag",
      "location": "betroffener Bereich/Selektor/Datei-Hinweis, falls erkennbar"
    }
  ]
}
Wenn alles gut ist: leeres findings-Array und hoher score. Sei streng aber fair.`,
  en: `You are an experienced QA engineer. Analyze the screenshot and console logs of a web page.
Respond ONLY with valid JSON (no markdown, no text before/after) in exactly this schema:
{
  "summary": "short overall assessment",
  "score": 0-100,
  "findings": [
    {
      "id": "short-unique",
      "title": "concise title",
      "severity": "low|medium|high|critical",
      "category": "ui|layout|visual|technical|accessibility|performance|content",
      "description": "what is the problem",
      "suggestedFix": "concrete, actionable fix",
      "location": "affected area/selector/file hint if discernible"
    }
  ]
}
If everything is fine: empty findings array and high score. Be strict but fair.`,
};

module.exports = { t, QA_SYSTEM_PROMPT, QA_STRUCTURED_PROMPT, qaUserMessage };
