"use strict";

/**
 * Schriftliche Dokumentation: Markdown-Reports für Release-Readiness und
 * den QA-Loop.
 */

const path = require("path");
const { writeText } = require("../util");

function findingsTable(findings, lang) {
  if (!findings || findings.length === 0) {
    return lang === "en" ? "_No findings._\n" : "_Keine Befunde._\n";
  }
  const head = lang === "en"
    ? "| Severity | Category | Title | Suggested fix |\n|---|---|---|---|\n"
    : "| Severity | Kategorie | Titel | Lösungsvorschlag |\n|---|---|---|---|\n";
  const rows = findings
    .map((f) => `| ${f.severity} | ${f.category} | ${f.title} | ${(f.suggestedFix || "").replace(/\n/g, " ")} |`)
    .join("\n");
  return head + rows + "\n";
}

/** Schreibt RELEASE-READINESS.md und gibt den Pfad zurück. */
function writeReleaseDoc({ url, release, findings, outDir, lang }) {
  const ready = release.ready ? "✅" : "❌";
  const md = `# Release Readiness

**URL:** ${url}
**Verdict:** ${ready} ${release.verdict}
**Score:** ${release.score}/100
**Timestamp:** ${new Date().toISOString()}

## Checkliste

${release.checklist.map((c) => `- [${c.ok ? "x" : " "}] ${c.label}`).join("\n")}

## Blocker (${release.blockers.length})

${release.blockers.length ? release.blockers.map((b) => `- ❌ ${b}`).join("\n") : (lang === "en" ? "_None._" : "_Keine._")}

## Warnungen (${release.warnings.length})

${release.warnings.length ? release.warnings.map((w) => `- ⚠️ ${w}`).join("\n") : (lang === "en" ? "_None._" : "_Keine._")}

## Befunde (${findings.length})

${findingsTable(findings, lang)}

---
*${lang === "en" ? "Generated by CUE-AGENT" : "Erzeugt von CUE-AGENT"}*
`;
  const p = path.join(outDir, "RELEASE-READINESS.md");
  writeText(p, md);
  return p;
}

/** Schreibt QA-LOOP.md mit allen Iterationen. */
function writeLoopDoc({ url, iterations, finalRelease, outDir, lang }) {
  const ready = finalRelease.ready ? "✅" : "❌";
  let md = `# QA-Loop Report

**URL:** ${url}
**Iterationen:** ${iterations.length}
**Endergebnis:** ${ready} ${finalRelease.verdict}
**Timestamp:** ${new Date().toISOString()}

`;
  for (const it of iterations) {
    md += `## Iteration ${it.n}\n\n`;
    md += `- Score: ${it.score}/100 — Verdict: ${it.release.ready ? "READY" : "NOT READY"}\n`;
    md += `- Befunde: ${it.findings.length} (${JSON.stringify(it.release.counts)})\n`;
    if (it.fixesProposed && it.fixesProposed.length) {
      md += `\n### Vorgeschlagene Fixes\n\n`;
      md += it.fixesProposed.map((f) => `- **${f.file}** — ${f.rationale || ""}`).join("\n") + "\n";
    }
    if (it.fixesApplied && it.fixesApplied.length) {
      md += `\n### Angewendete Fixes\n\n`;
      md += it.fixesApplied.map((f) => `- ✏️ ${f.file}`).join("\n") + "\n";
    }
    if (it.rebuild) md += `\n- Rebuild: \`${it.rebuild.cmd}\` → ${it.rebuild.ok ? "ok" : "FEHLER"}\n`;
    md += `\n### Befunde\n\n${findingsTable(it.findings, lang)}\n`;
  }
  md += `\n---\n*${lang === "en" ? "Generated by CUE-AGENT" : "Erzeugt von CUE-AGENT"}*\n`;
  const p = path.join(outDir, "QA-LOOP.md");
  writeText(p, md);
  return p;
}

module.exports = { writeReleaseDoc, writeLoopDoc, findingsTable };
